#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"


# Enable autocomplete layer
[[layers]]
    name = "autocomplete"
    auto_completion_return_key_behavior = "complete"
    auto_completion_tab_key_behavior = "smart"

[[layers]]
    name = "shell"
    default_position = "top"
    default_height = 30

[[layers]]
    name = "format"

[[layers]]
    name = "denite"

[[layers]]
    name = "git"
    git_plugin = "fugitive"

[[layers]]
    name = "github"

[[layers]]
    name = "tmux"

[[layers]]
    name = "foldsearch"

[[custom_plugins]]
    repo = "junegunn/fzf"
    merged = false

[[custom_plugins]]
    repo = "junegunn/fzf.vim"
    merged = false

[[custom_plugins]]
    repo = "github/copilot.vim"
    merged = false
