# Personal Zsh configuration file. It is strongly recommended to keep all
# shell customization and configuration (including exported environment
# variables such as PATH) in this file or in files sourced from it.
#
# Documentation: https://github.com/romkatv/zsh4humans/blob/v5/README.md.

# Periodic auto-update on Zsh startup: 'ask' or 'no'.
# You can manually run `z4h update` to update everything.
zstyle ':z4h:' auto-update      'no'
# Ask whether to auto-update this often; has no effect if auto-update is 'no'.
zstyle ':z4h:' auto-update-days '28'

# Move prompt to the bottom when zsh starts and on Ctrl+L.
zstyle ':z4h:' prompt-at-bottom 'no'

# Keyboard type: 'mac' or 'pc'.
zstyle ':z4h:bindkey' keyboard  'mac'

# Start tmux if not already in tmux.
zstyle ':z4h:' start-tmux command tmux -u new
# zstyle ':z4h:' start-tmux system

# Mark up shell's output with semantic information.
zstyle ':z4h:' term-shell-integration 'yes'

# Right-arrow key accepts one character ('partial-accept') from
# command autosuggestions or the whole thing ('accept')?
zstyle ':z4h:autosuggestions' forward-char 'accept'

# Recursively traverse directories when TAB-completing files.
zstyle ':z4h:fzf-complete' recurse-dirs 'no'

# Enable direnv to automatically source .envrc files.
zstyle ':z4h:direnv'         enable 'no'
# Show "loading" and "unloading" notifications from direnv.
zstyle ':z4h:direnv:success' notify 'yes'

# Enable ('yes') or disable ('no') automatic teleportation of z4h over
# SSH when connecting to these hosts.
zstyle ':z4h:ssh:example-hostname1'   enable 'yes'
zstyle ':z4h:ssh:*.example-hostname2' enable 'no'
# The default value if none of the overrides above match the hostname.
zstyle ':z4h:ssh:*'                   enable 'no'

# Send these files over to the remote host when connecting over SSH to the
# enabled hosts.
zstyle ':z4h:ssh:*' send-extra-files '~/.nanorc' '~/.env.zsh'

# Clone additional Git repositories from GitHub.
#
# This doesn't do anything apart from cloning the repository and keeping it
# up-to-date. Cloned files can be used after `z4h init`. This is just an
# example. If you don't plan to use Oh My Zsh, delete this line.
z4h install ohmyzsh/ohmyzsh || return
z4h install garodriguezlp/dotfiles@main || return

# Install or update core components (fzf, zsh-autosuggestions, etc.) and
# initialize Zsh. After this point console I/O is unavailable until Zsh
# is fully initialized. Everything that requires user interaction or can
# perform network I/O must be done above. Everything else is best done below.
z4h init || return

# Extend PATH.
path=(~/bin $path)

# Export environment variables.
export GPG_TTY=$TTY

# Source additional local files if they exist.
z4h source ~/.env.zsh

# Use additional Git repositories pulled in with `z4h install`.
#
# This is just an example that you should delete. It does nothing useful.
z4h source ohmyzsh/ohmyzsh/lib/diagnostics.zsh  # source an individual file
z4h source ohmyzsh/ohmyzsh/lib/git.zsh  # source an individual file
z4h load   ohmyzsh/ohmyzsh/plugins/aliases
z4h load   ohmyzsh/ohmyzsh/plugins/autojump
z4h load   ohmyzsh/ohmyzsh/plugins/brew
z4h load   ohmyzsh/ohmyzsh/plugins/common-aliases
z4h load   ohmyzsh/ohmyzsh/plugins/direnv
z4h load   ohmyzsh/ohmyzsh/plugins/extract
z4h load   ohmyzsh/ohmyzsh/plugins/fzf
z4h load   ohmyzsh/ohmyzsh/plugins/git
z4h load   ohmyzsh/ohmyzsh/plugins/github
z4h load   ohmyzsh/ohmyzsh/plugins/gitignore
z4h load   ohmyzsh/ohmyzsh/plugins/gradle
z4h load   ohmyzsh/ohmyzsh/plugins/httpie
z4h load   ohmyzsh/ohmyzsh/plugins/mvn
z4h load   ohmyzsh/ohmyzsh/plugins/nvm
z4h load   ohmyzsh/ohmyzsh/plugins/sdk
z4h load   ohmyzsh/ohmyzsh/plugins/thefuck
z4h load   ohmyzsh/ohmyzsh/plugins/tmux
z4h load   ohmyzsh/ohmyzsh/plugins/web-search
z4h load   garodriguezlp/dotfiles/plugins/fzf
z4h load   garodriguezlp/dotfiles/plugins/jbang
z4h load   garodriguezlp/dotfiles/plugins/key-bindings
z4h load   garodriguezlp/dotfiles/plugins/milli-misc
z4h load   garodriguezlp/dotfiles/plugins/milli-cli
z4h load   garodriguezlp/dotfiles/plugins/node-16-homebrew
z4h load   garodriguezlp/dotfiles/plugins/nvim
z4h load   garodriguezlp/dotfiles/plugins/sdk
z4h load   garodriguezlp/dotfiles/plugins/fun
z4h load   $HOME/src/milli/gustavo/zsh-plugins/milli-app
z4h load   $HOME/src/milli/gustavo/zsh-plugins/milli-glab

z4h source   $HOME/.secrets.zsh

# In order to avoid conflicts with `sdkman` this needs to be loaded after
z4h load   ohmyzsh/ohmyzsh/plugins/jenv

# Define key bindings.
z4h bindkey undo Ctrl+/   Shift+Tab  # undo the last command line change
z4h bindkey redo Option+/            # redo the last undone command line change

z4h bindkey z4h-cd-back    Shift+Left   # cd into the previous directory
z4h bindkey z4h-cd-forward Shift+Right  # cd into the next directory
z4h bindkey z4h-cd-up      Shift+Up     # cd into the parent directory
z4h bindkey z4h-cd-down    Shift+Down   # cd into a child directory

# Autoload functions.
autoload -Uz zmv

# Define functions and completions.
function md() { [[ $# == 1 ]] && mkdir -p -- "$1" && cd -- "$1" }
compdef _directories md

# Define named directories: ~w <=> Windows home directory on WSL.
[[ -z $z4h_win_home ]] || hash -d w=$z4h_win_home

# Define aliases.
alias tree='tree -a -I .git'

# Add flags to existing aliases.
alias ls="${aliases[ls]:-ls} -A"

# Set shell options: http://zsh.sourceforge.net/Doc/Release/Options.html.
setopt glob_dots     # no special treatment for file names with a leading dot
setopt no_auto_menu  # require an extra TAB press to open the completion menu
