- defaults:
    shell:
        stdin: true
        stdout: true
        stderr: true
    link:
        relink: true
        force: true
        create: true

- link:
    ~/:
      glob: true
      path: dotfiles/*
      prefix: '.'
    ~/.zshrc:
        path: codespaces/dotfiles/zshrc
